### PR TITLE
Introducing first math functionality

### LINKED ISSUE #1: [Feature Request]: Include math module
### What should be implemented?

Add a math module that might include:
https://github.com/jayPi4c/Matrix
https://github.com/jayPi4c/polynomial
and further math related stuff.

### PR DESCRIPTION
**Pull request by JayPi4c**
Introducing first math module functionality.

Please help me decide naming the package correctly. I think they are all part of algebra so I guess, it would be appropriate to move them in the `org.schlunzis.zis.math.algebra` package.

Task to be completed until PR is ready:

- [x] Create tests for all classes
- [x] Add missing javadoc comments
~~(optional) refactor methods to fulfill best practices~~

closes #1

### CODE REVIEW

**Comment by Til7701** [comment]
1. Apache Commons uses `linear` since it is linear algebra, but I would be fine with algebra. I don`t think we will be adding to many algebra related classes.
2. How do we want to handle `@since` and `@author` in the JavaDoc? Do we want to let Git handle to author part and add the since to all JavaDoc instances?

**Comment by JayPi4c** [comment]
To 1. I'm okay with naming the packages `linear` and `analysis` for `Matrix` and `Polynomial` respectively.
To 2. I plan on updating the JavaDoc for the classes to contain the `@since` tag with the correct version in which it was introduced to `zis`. So it would be `0.0.1` for this PR. Regarding the second part: I'm a little confused about how git can handle the `@author` tag in the JavaDoc. Please enlighten me.

**Comment by Til7701** [comment]
Git blame can accurately tell anyone, who implemented the feature. Its not in the JavaDoc, so users oft the library might not see it, but the author tag cannot show collaborative work as well as git.

**Comment by JayPi4c** [comment]
Okay. Now I understand. Maybe we should think of `@author` as something that marks who is assigned to that class in case of any questions. If it is multiple persons, then it is okay to use multiple `@author` tags. `git blame` will tell the accurate details of who did what but `@author` will give a brief overview of who is in charge. Also I think we should only use the `@author` tag on the class level and not for methods or attributes (there might be some exceptions but generally this could be considered as a rule of thumbs),

**Review by Til7701 — APPROVED** [review]

**Pull request merged**
